modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="weapons"
version="${version}"
displayName="Weapons Mod"
authors="MinhPhuc00ne"
description='''
Mod Vu Khi (Weapons Mod) - Ho tro da nen tang Fabric va Forge
'''

[[dependencies.weapons]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.weapons]]
    modId="architectury"
    mandatory=true
    versionRange="[9.2.14,)"
    ordering="NONE"
    side="BOTH"
